-- 코드를 입력하세요
SELECT REST_INFO.REST_ID AS REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(REST_REVIEW.REVIEW_SCORE), 2) AS SCORE
FROM REST_REVIEW JOIN REST_INFO ON REST_INFO.REST_ID = REST_REVIEW.REST_ID
WHERE REST_INFO.ADDRESS LIKE "서울%"
GROUP BY REST_INFO.REST_ID
ORDER BY ROUND(AVG(REST_REVIEW.REVIEW_SCORE), 2) DESC, REST_INFO.FAVORITES DESC;